### ISSUE TITLE
NG cockpit is used to manage customers & organizations entities

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_denis#11]
As a **content manager**
I want to be able to change customers and organizations attributes in more modern way
So that backoffice extension is added to B2C accelerator

**AC:**
1. Organizations node is added to backoffice objects tree
2. Organizations manager is able to perform CRUD-operations with organizations & customers via backoffice web-page.
3. Organizations are created via a specially developed wizard

*Tips:*
https://wiki.hybris.com/display/release5/Include+-+Create+a+Custom+Backoffice+Extension 
https://wiki.hybris.com/display/tr52/Trail+~+Customizing+Backoffice+-+Cockpit+NG

**Comment by kohanevich85** [comment]
![ng cockpit_1](https://cloud.githubusercontent.com/assets/3422104/17135889/d14535e8-533a-11e6-955e-261ae2cf2b8c.png)
******************************************
![ng cockpit_2](https://cloud.githubusercontent.com/assets/3422104/17135890/d354ed9c-533a-11e6-9436-134b44b20bc6.png)
********************************
![ng cockpit_3](https://cloud.githubusercontent.com/assets/3422104/17135898/ddea0486-533a-11e6-8ba1-c6fe93431f53.png)
*******************************
![ng cockpit_4](https://cloud.githubusercontent.com/assets/3422104/17135910/eeb03146-533a-11e6-89a1-dd2c7850adbd.png)
*******************************
![ng cockpit_5](https://cloud.githubusercontent.com/assets/3422104/17135912/f37668f8-533a-11e6-8808-9d04b65e27d4.png)
******************************
