### ISSUE TITLE
Let organization customers receive e-mails

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_denis#12]
As an **organization manager**
I want to be on the same page with organization contents
So that I receive daily email with list of users in my organization

**AC**
Email is sent to each organization manager whose address is set as an Organization.email attribute.
The email should contain list of all users in this organization. 

**Mail server configuration**
mail.from=/gmail account/
mail.replyto=/gmail account/
mail.smtp.server=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=/gmail account/
mail.smtp.password=/gmail password/
mail.smtp.starttls.enable=true
mail.use.tls=true

**Comment by kohanevich85** [comment]
![receive_e-mails_1](https://cloud.githubusercontent.com/assets/3422104/17193328/420b20a0-545b-11e6-8ccb-4eb4427af764.png)
*********************************
![receive_e-mails_2](https://cloud.githubusercontent.com/assets/3422104/17193329/439e06da-545b-11e6-9dc3-ebce33570df1.png)
