### ISSUE TITLE
Run "organization e-mails" job using ant (without hybris started)

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_denis#13]
As hybris **admin user**
I want to have a possibility to start "organization e-mails" cronjob without having hybris started
So that I have a bat script that starts this cronjob using ant.

**AC**
Needed .bat (or .sh) script is placed into a separate "admin" folder.

*Tips*
https://wiki.hybris.com/display/release5/cronjob+-+Technical+Guide#cronjob-TechnicalGuide-RunningCronJobsThroughAnt

**Comment by kohanevich85** [comment]
![job using ant_1](https://cloud.githubusercontent.com/assets/3422104/17210917/be96bbac-54ce-11e6-8c94-e74c56d22f5a.png)
***********************************
![job using ant_2](https://cloud.githubusercontent.com/assets/3422104/17210919/c3356f32-54ce-11e6-8679-d6b673cc957d.png)
