### ISSUE TITLE
Obtain list of organizations via webservices

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_denis#14]
As a **mobile developer or developer of integration candidate utility**
I want to have a possibility to obtain list of organizations via REST calls
So that webservices extension is configured properly

**AC**
Webservices extension is turned-on for B2C accelerator
Appropriate controllers are written
jUnit tests are written to test the functionality

*Tips:*
https://wiki.hybris.com/display/release5/Introduction+to+Web+Services
https://wiki.hybris.com/display/release5/Key+Features+and+Implementation+Details

**Comment by kohanevich85** [comment]
![webservices_1](https://cloud.githubusercontent.com/assets/3422104/17248651/8f07a03c-55a4-11e6-8deb-cb976506abd8.png)
