### ISSUE TITLE
Generate an error message when organization name length is greater than 15 simbols

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_denis#15]
As a **content manager**
I want to have a constraint for organization's name attribute
So that an appropriate constraint is created via ImpEx and is available in Admin cockpit.

**AC**
Aftert an attempt to set a long value for organization name an appropriate contraint generated an error
Constraint is created using ImpEx and could be changed in Admin cockpit

*Tips:*
https://wiki.hybris.com/display/R5T/Trail+~+Validation

**Comment by kohanevich85** [comment]
![constraint_1](https://cloud.githubusercontent.com/assets/3422104/17288614/b7f2bd92-57de-11e6-9587-cca77aa5d787.png)
*****************************
![constraint_2](https://cloud.githubusercontent.com/assets/3422104/17288620/bd23d6ac-57de-11e6-994d-c967fd4c9d35.png)
