### ISSUE TITLE
Interceptor is created to listen to organization fields change

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_denis#16]
As **organization's customer**
I want to receive e-mail message when an amount of customers that belong to my organization becomes equal to 5
So that an appropriate intercepor is created to listen to such events.

**AC**
Each organization customer receives an e-mail message when its amount of customers becomes equal to 5

*Tips*
https://wiki.hybris.com/display/release5/Registering+Application+Event+Listener
https://wiki.hybris.com/display/release5/Event+System

**Comment by kohanevich85** [comment]
![customer_amount_email](https://cloud.githubusercontent.com/assets/3422104/17293680/775c6c4e-57fa-11e6-8d4f-844dc81b5418.png)
*************************************
![customer_amount_email_2](https://cloud.githubusercontent.com/assets/3422104/17293685/7c7a65a0-57fa-11e6-9f8b-31905a72b348.png)
***************************************
![customer_amount_email_3](https://cloud.githubusercontent.com/assets/3422104/17293689/80e9557e-57fa-11e6-8fbf-057be29a92c8.png)
