### ISSUE TITLE
Change default HAC URL to be “/hac”

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_denis#17]
As **hybris admin** 
I want to have more flexible way to access hAC
So that to perform an access to hybris Admin Console I use "http://{host:port}/hac" URL

**AC**
Access to hAC is performer after sending a request to "http://{host:port}/hac" URL

*Tips*
local.properties file
hac.webroot && hmc.webroot properties there

**Comment by kohanevich85** [comment]
![hac](https://cloud.githubusercontent.com/assets/3422104/17294709/03c02cba-5801-11e6-90f8-62346a397a42.png)
